(function () {
  "use strict";
  var QURAN_SURAHS = [
    { number: 1, nameArabic: "الفاتحة", nameSimple: "Al-Fatihah", nameTranslated: "The Opener", versesCount: 7, revelationPlace: "makkah" },
    { number: 2, nameArabic: "البقرة", nameSimple: "Al-Baqarah", nameTranslated: "The Cow", versesCount: 286, revelationPlace: "madinah" },
    { number: 3, nameArabic: "آل عمران", nameSimple: "Ali 'Imran", nameTranslated: "Family of Imran", versesCount: 200, revelationPlace: "madinah" },
    { number: 4, nameArabic: "النساء", nameSimple: "An-Nisa", nameTranslated: "The Women", versesCount: 176, revelationPlace: "madinah" },
    { number: 5, nameArabic: "المائدة", nameSimple: "Al-Ma'idah", nameTranslated: "The Table Spread", versesCount: 120, revelationPlace: "madinah" },
    { number: 6, nameArabic: "الأنعام", nameSimple: "Al-An'am", nameTranslated: "The Cattle", versesCount: 165, revelationPlace: "makkah" },
    { number: 7, nameArabic: "الأعراف", nameSimple: "Al-A'raf", nameTranslated: "The Heights", versesCount: 206, revelationPlace: "makkah" },
    { number: 8, nameArabic: "الأنفال", nameSimple: "Al-Anfal", nameTranslated: "The Spoils of War", versesCount: 75, revelationPlace: "madinah" },
    { number: 9, nameArabic: "التوبة", nameSimple: "At-Tawbah", nameTranslated: "The Repentance", versesCount: 129, revelationPlace: "madinah" },
    { number: 10, nameArabic: "يونس", nameSimple: "Yunus", nameTranslated: "Jonah", versesCount: 109, revelationPlace: "makkah" },
    { number: 11, nameArabic: "هود", nameSimple: "Hud", nameTranslated: "Hud", versesCount: 123, revelationPlace: "makkah" },
    { number: 12, nameArabic: "يوسف", nameSimple: "Yusuf", nameTranslated: "Joseph", versesCount: 111, revelationPlace: "makkah" },
    { number: 13, nameArabic: "الرعد", nameSimple: "Ar-Ra'd", nameTranslated: "The Thunder", versesCount: 43, revelationPlace: "madinah" },
    { number: 14, nameArabic: "ابراهيم", nameSimple: "Ibrahim", nameTranslated: "Abraham", versesCount: 52, revelationPlace: "makkah" },
    { number: 15, nameArabic: "الحجر", nameSimple: "Al-Hijr", nameTranslated: "The Rocky Tract", versesCount: 99, revelationPlace: "makkah" },
    { number: 16, nameArabic: "النحل", nameSimple: "An-Nahl", nameTranslated: "The Bee", versesCount: 128, revelationPlace: "makkah" },
    { number: 17, nameArabic: "الإسراء", nameSimple: "Al-Isra", nameTranslated: "The Night Journey", versesCount: 111, revelationPlace: "makkah" },
    { number: 18, nameArabic: "الكهف", nameSimple: "Al-Kahf", nameTranslated: "The Cave", versesCount: 110, revelationPlace: "makkah" },
    { number: 19, nameArabic: "مريم", nameSimple: "Maryam", nameTranslated: "Mary", versesCount: 98, revelationPlace: "makkah" },
    { number: 20, nameArabic: "طه", nameSimple: "Taha", nameTranslated: "Ta-Ha", versesCount: 135, revelationPlace: "makkah" },
    { number: 21, nameArabic: "الأنبياء", nameSimple: "Al-Anbya", nameTranslated: "The Prophets", versesCount: 112, revelationPlace: "makkah" },
    { number: 22, nameArabic: "الحج", nameSimple: "Al-Hajj", nameTranslated: "The Pilgrimage", versesCount: 78, revelationPlace: "madinah" },
    { number: 23, nameArabic: "المؤمنون", nameSimple: "Al-Mu'minun", nameTranslated: "The Believers", versesCount: 118, revelationPlace: "makkah" },
    { number: 24, nameArabic: "النور", nameSimple: "An-Nur", nameTranslated: "The Light", versesCount: 64, revelationPlace: "madinah" },
    { number: 25, nameArabic: "الفرقان", nameSimple: "Al-Furqan", nameTranslated: "The Criterion", versesCount: 77, revelationPlace: "makkah" },
    { number: 26, nameArabic: "الشعراء", nameSimple: "Ash-Shu'ara", nameTranslated: "The Poets", versesCount: 227, revelationPlace: "makkah" },
    { number: 27, nameArabic: "النمل", nameSimple: "An-Naml", nameTranslated: "The Ant", versesCount: 93, revelationPlace: "makkah" },
    { number: 28, nameArabic: "القصص", nameSimple: "Al-Qasas", nameTranslated: "The Stories", versesCount: 88, revelationPlace: "makkah" },
    { number: 29, nameArabic: "العنكبوت", nameSimple: "Al-'Ankabut", nameTranslated: "The Spider", versesCount: 69, revelationPlace: "makkah" },
    { number: 30, nameArabic: "الروم", nameSimple: "Ar-Rum", nameTranslated: "The Romans", versesCount: 60, revelationPlace: "makkah" },
    { number: 31, nameArabic: "لقمان", nameSimple: "Luqman", nameTranslated: "Luqman", versesCount: 34, revelationPlace: "makkah" },
    { number: 32, nameArabic: "السجدة", nameSimple: "As-Sajdah", nameTranslated: "The Prostration", versesCount: 30, revelationPlace: "makkah" },
    { number: 33, nameArabic: "الأحزاب", nameSimple: "Al-Ahzab", nameTranslated: "The Combined Forces", versesCount: 73, revelationPlace: "madinah" },
    { number: 34, nameArabic: "سبإ", nameSimple: "Saba", nameTranslated: "Sheba", versesCount: 54, revelationPlace: "makkah" },
    { number: 35, nameArabic: "فاطر", nameSimple: "Fatir", nameTranslated: "Originator", versesCount: 45, revelationPlace: "makkah" },
    { number: 36, nameArabic: "يس", nameSimple: "Ya-Sin", nameTranslated: "Ya Sin", versesCount: 83, revelationPlace: "makkah" },
    { number: 37, nameArabic: "الصافات", nameSimple: "As-Saffat", nameTranslated: "Those who set the Ranks", versesCount: 182, revelationPlace: "makkah" },
    { number: 38, nameArabic: "ص", nameSimple: "Sad", nameTranslated: "The Letter \"Saad\"", versesCount: 88, revelationPlace: "makkah" },
    { number: 39, nameArabic: "الزمر", nameSimple: "Az-Zumar", nameTranslated: "The Troops", versesCount: 75, revelationPlace: "makkah" },
    { number: 40, nameArabic: "غافر", nameSimple: "Ghafir", nameTranslated: "The Forgiver", versesCount: 85, revelationPlace: "makkah" },
    { number: 41, nameArabic: "فصلت", nameSimple: "Fussilat", nameTranslated: "Explained in Detail", versesCount: 54, revelationPlace: "makkah" },
    { number: 42, nameArabic: "الشورى", nameSimple: "Ash-Shuraa", nameTranslated: "The Consultation", versesCount: 53, revelationPlace: "makkah" },
    { number: 43, nameArabic: "الزخرف", nameSimple: "Az-Zukhruf", nameTranslated: "The Ornaments of Gold", versesCount: 89, revelationPlace: "makkah" },
    { number: 44, nameArabic: "الدخان", nameSimple: "Ad-Dukhan", nameTranslated: "The Smoke", versesCount: 59, revelationPlace: "makkah" },
    { number: 45, nameArabic: "الجاثية", nameSimple: "Al-Jathiyah", nameTranslated: "The Crouching", versesCount: 37, revelationPlace: "makkah" },
    { number: 46, nameArabic: "الأحقاف", nameSimple: "Al-Ahqaf", nameTranslated: "The Wind-Curved Sandhills", versesCount: 35, revelationPlace: "makkah" },
    { number: 47, nameArabic: "محمد", nameSimple: "Muhammad", nameTranslated: "Muhammad", versesCount: 38, revelationPlace: "madinah" },
    { number: 48, nameArabic: "الفتح", nameSimple: "Al-Fath", nameTranslated: "The Victory", versesCount: 29, revelationPlace: "madinah" },
    { number: 49, nameArabic: "الحجرات", nameSimple: "Al-Hujurat", nameTranslated: "The Rooms", versesCount: 18, revelationPlace: "madinah" },
    { number: 50, nameArabic: "ق", nameSimple: "Qaf", nameTranslated: "The Letter \"Qaf\"", versesCount: 45, revelationPlace: "makkah" },
    { number: 51, nameArabic: "الذاريات", nameSimple: "Adh-Dhariyat", nameTranslated: "The Winnowing Winds", versesCount: 60, revelationPlace: "makkah" },
    { number: 52, nameArabic: "الطور", nameSimple: "At-Tur", nameTranslated: "The Mount", versesCount: 49, revelationPlace: "makkah" },
    { number: 53, nameArabic: "النجم", nameSimple: "An-Najm", nameTranslated: "The Star", versesCount: 62, revelationPlace: "makkah" },
    { number: 54, nameArabic: "القمر", nameSimple: "Al-Qamar", nameTranslated: "The Moon", versesCount: 55, revelationPlace: "makkah" },
    { number: 55, nameArabic: "الرحمن", nameSimple: "Ar-Rahman", nameTranslated: "The Beneficent", versesCount: 78, revelationPlace: "madinah" },
    { number: 56, nameArabic: "الواقعة", nameSimple: "Al-Waqi'ah", nameTranslated: "The Inevitable", versesCount: 96, revelationPlace: "makkah" },
    { number: 57, nameArabic: "الحديد", nameSimple: "Al-Hadid", nameTranslated: "The Iron", versesCount: 29, revelationPlace: "madinah" },
    { number: 58, nameArabic: "المجادلة", nameSimple: "Al-Mujadila", nameTranslated: "The Pleading Woman", versesCount: 22, revelationPlace: "madinah" },
    { number: 59, nameArabic: "الحشر", nameSimple: "Al-Hashr", nameTranslated: "The Exile", versesCount: 24, revelationPlace: "madinah" },
    { number: 60, nameArabic: "الممتحنة", nameSimple: "Al-Mumtahanah", nameTranslated: "She that is to be examined", versesCount: 13, revelationPlace: "madinah" },
    { number: 61, nameArabic: "الصف", nameSimple: "As-Saf", nameTranslated: "The Ranks", versesCount: 14, revelationPlace: "madinah" },
    { number: 62, nameArabic: "الجمعة", nameSimple: "Al-Jumu'ah", nameTranslated: "The Congregation, Friday", versesCount: 11, revelationPlace: "madinah" },
    { number: 63, nameArabic: "المنافقون", nameSimple: "Al-Munafiqun", nameTranslated: "The Hypocrites", versesCount: 11, revelationPlace: "madinah" },
    { number: 64, nameArabic: "التغابن", nameSimple: "At-Taghabun", nameTranslated: "The Mutual Disillusion", versesCount: 18, revelationPlace: "madinah" },
    { number: 65, nameArabic: "الطلاق", nameSimple: "At-Talaq", nameTranslated: "The Divorce", versesCount: 12, revelationPlace: "madinah" },
    { number: 66, nameArabic: "التحريم", nameSimple: "At-Tahrim", nameTranslated: "The Prohibition", versesCount: 12, revelationPlace: "madinah" },
    { number: 67, nameArabic: "الملك", nameSimple: "Al-Mulk", nameTranslated: "The Sovereignty", versesCount: 30, revelationPlace: "makkah" },
    { number: 68, nameArabic: "القلم", nameSimple: "Al-Qalam", nameTranslated: "The Pen", versesCount: 52, revelationPlace: "makkah" },
    { number: 69, nameArabic: "الحاقة", nameSimple: "Al-Haqqah", nameTranslated: "The Reality", versesCount: 52, revelationPlace: "makkah" },
    { number: 70, nameArabic: "المعارج", nameSimple: "Al-Ma'arij", nameTranslated: "The Ascending Stairways", versesCount: 44, revelationPlace: "makkah" },
    { number: 71, nameArabic: "نوح", nameSimple: "Nuh", nameTranslated: "Noah", versesCount: 28, revelationPlace: "makkah" },
    { number: 72, nameArabic: "الجن", nameSimple: "Al-Jinn", nameTranslated: "The Jinn", versesCount: 28, revelationPlace: "makkah" },
    { number: 73, nameArabic: "المزمل", nameSimple: "Al-Muzzammil", nameTranslated: "The Enshrouded One", versesCount: 20, revelationPlace: "makkah" },
    { number: 74, nameArabic: "المدثر", nameSimple: "Al-Muddaththir", nameTranslated: "The Cloaked One", versesCount: 56, revelationPlace: "makkah" },
    { number: 75, nameArabic: "القيامة", nameSimple: "Al-Qiyamah", nameTranslated: "The Resurrection", versesCount: 40, revelationPlace: "makkah" },
    { number: 76, nameArabic: "الانسان", nameSimple: "Al-Insan", nameTranslated: "The Man", versesCount: 31, revelationPlace: "madinah" },
    { number: 77, nameArabic: "المرسلات", nameSimple: "Al-Mursalat", nameTranslated: "The Emissaries", versesCount: 50, revelationPlace: "makkah" },
    { number: 78, nameArabic: "النبإ", nameSimple: "An-Naba", nameTranslated: "The Tidings", versesCount: 40, revelationPlace: "makkah" },
    { number: 79, nameArabic: "النازعات", nameSimple: "An-Nazi'at", nameTranslated: "Those who drag forth", versesCount: 46, revelationPlace: "makkah" },
    { number: 80, nameArabic: "عبس", nameSimple: "'Abasa", nameTranslated: "He Frowned", versesCount: 42, revelationPlace: "makkah" },
    { number: 81, nameArabic: "التكوير", nameSimple: "At-Takwir", nameTranslated: "The Overthrowing", versesCount: 29, revelationPlace: "makkah" },
    { number: 82, nameArabic: "الإنفطار", nameSimple: "Al-Infitar", nameTranslated: "The Cleaving", versesCount: 19, revelationPlace: "makkah" },
    { number: 83, nameArabic: "المطففين", nameSimple: "Al-Mutaffifin", nameTranslated: "The Defrauding", versesCount: 36, revelationPlace: "makkah" },
    { number: 84, nameArabic: "الإنشقاق", nameSimple: "Al-Inshiqaq", nameTranslated: "The Sundering", versesCount: 25, revelationPlace: "makkah" },
    { number: 85, nameArabic: "البروج", nameSimple: "Al-Buruj", nameTranslated: "The Mansions of the Stars", versesCount: 22, revelationPlace: "makkah" },
    { number: 86, nameArabic: "الطارق", nameSimple: "At-Tariq", nameTranslated: "The Nightcommer", versesCount: 17, revelationPlace: "makkah" },
    { number: 87, nameArabic: "الأعلى", nameSimple: "Al-A'la", nameTranslated: "The Most High", versesCount: 19, revelationPlace: "makkah" },
    { number: 88, nameArabic: "الغاشية", nameSimple: "Al-Ghashiyah", nameTranslated: "The Overwhelming", versesCount: 26, revelationPlace: "makkah" },
    { number: 89, nameArabic: "الفجر", nameSimple: "Al-Fajr", nameTranslated: "The Dawn", versesCount: 30, revelationPlace: "makkah" },
    { number: 90, nameArabic: "البلد", nameSimple: "Al-Balad", nameTranslated: "The City", versesCount: 20, revelationPlace: "makkah" },
    { number: 91, nameArabic: "الشمس", nameSimple: "Ash-Shams", nameTranslated: "The Sun", versesCount: 15, revelationPlace: "makkah" },
    { number: 92, nameArabic: "الليل", nameSimple: "Al-Layl", nameTranslated: "The Night", versesCount: 21, revelationPlace: "makkah" },
    { number: 93, nameArabic: "الضحى", nameSimple: "Ad-Duhaa", nameTranslated: "The Morning Hours", versesCount: 11, revelationPlace: "makkah" },
    { number: 94, nameArabic: "الشرح", nameSimple: "Ash-Sharh", nameTranslated: "The Relief", versesCount: 8, revelationPlace: "makkah" },
    { number: 95, nameArabic: "التين", nameSimple: "At-Tin", nameTranslated: "The Fig", versesCount: 8, revelationPlace: "makkah" },
    { number: 96, nameArabic: "العلق", nameSimple: "Al-'Alaq", nameTranslated: "The Clot", versesCount: 19, revelationPlace: "makkah" },
    { number: 97, nameArabic: "القدر", nameSimple: "Al-Qadr", nameTranslated: "The Power", versesCount: 5, revelationPlace: "makkah" },
    { number: 98, nameArabic: "البينة", nameSimple: "Al-Bayyinah", nameTranslated: "The Clear Proof", versesCount: 8, revelationPlace: "madinah" },
    { number: 99, nameArabic: "الزلزلة", nameSimple: "Az-Zalzalah", nameTranslated: "The Earthquake", versesCount: 8, revelationPlace: "madinah" },
    { number: 100, nameArabic: "العاديات", nameSimple: "Al-'Adiyat", nameTranslated: "The Courser", versesCount: 11, revelationPlace: "makkah" },
    { number: 101, nameArabic: "القارعة", nameSimple: "Al-Qari'ah", nameTranslated: "The Calamity", versesCount: 11, revelationPlace: "makkah" },
    { number: 102, nameArabic: "التكاثر", nameSimple: "At-Takathur", nameTranslated: "The Rivalry in world increase", versesCount: 8, revelationPlace: "makkah" },
    { number: 103, nameArabic: "العصر", nameSimple: "Al-'Asr", nameTranslated: "The Declining Day", versesCount: 3, revelationPlace: "makkah" },
    { number: 104, nameArabic: "الهمزة", nameSimple: "Al-Humazah", nameTranslated: "The Traducer", versesCount: 9, revelationPlace: "makkah" },
    { number: 105, nameArabic: "الفيل", nameSimple: "Al-Fil", nameTranslated: "The Elephant", versesCount: 5, revelationPlace: "makkah" },
    { number: 106, nameArabic: "قريش", nameSimple: "Quraysh", nameTranslated: "Quraysh", versesCount: 4, revelationPlace: "makkah" },
    { number: 107, nameArabic: "الماعون", nameSimple: "Al-Ma'un", nameTranslated: "The Small kindnesses", versesCount: 7, revelationPlace: "makkah" },
    { number: 108, nameArabic: "الكوثر", nameSimple: "Al-Kawthar", nameTranslated: "The Abundance", versesCount: 3, revelationPlace: "makkah" },
    { number: 109, nameArabic: "الكافرون", nameSimple: "Al-Kafirun", nameTranslated: "The Disbelievers", versesCount: 6, revelationPlace: "makkah" },
    { number: 110, nameArabic: "النصر", nameSimple: "An-Nasr", nameTranslated: "The Divine Support", versesCount: 3, revelationPlace: "madinah" },
    { number: 111, nameArabic: "المسد", nameSimple: "Al-Masad", nameTranslated: "The Palm Fiber", versesCount: 5, revelationPlace: "makkah" },
    { number: 112, nameArabic: "الإخلاص", nameSimple: "Al-Ikhlas", nameTranslated: "The Sincerity", versesCount: 4, revelationPlace: "makkah" },
    { number: 113, nameArabic: "الفلق", nameSimple: "Al-Falaq", nameTranslated: "The Daybreak", versesCount: 5, revelationPlace: "makkah" },
    { number: 114, nameArabic: "الناس", nameSimple: "An-Nas", nameTranslated: "Mankind", versesCount: 6, revelationPlace: "makkah" },
  ];
  window.NURA_QURAN_SURAHS = QURAN_SURAHS;
})();